version: '3.8'

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
    command: tail -f /dev/null

  node2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
    command: tail -f /dev/null

  node3:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
    command: tail -f /dev/null
